Practical Application:
1)	Create an array containing 4 string elements: your first name, your last name, your birth state and your favorite color. 
a.	Use a numpy function to make all elements uppercase. 
b.	Use a numpy function to count the number of times the letter “a” appears in each element of your array.
c.	Optional: Use a numpy function to find the length of each element in the array. You may need to Google this. 
2)	Create an array containing EVERY OTHER odd number starting with 1 and ending with (and including) 45. 
a.	Use numpy to find the sum and the product of the elements of this array.
b.	Use numpy to take the natural log of each element.
c.	Optional: The numpy function np.diff finds the difference between adjacent elements of an array. Find the SUM of adjacent elements of this array. 


In [1]:
import numpy as np
from datascience import *
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

In [2]:
#1) Create an array containing 4 string elements: your first name, your last name, your birth state and your favorite color.
four_strings = make_array('Pierce','Pluemer','7 Jan 1996','Blue')
four_strings

array(['Pierce', 'Pluemer', '7 Jan 1996', 'Blue'], dtype='<U10')

In [3]:
#a. Use a numpy function to make all elements uppercase.
np.char.upper(four_strings)

array(['PIERCE', 'PLUEMER', '7 JAN 1996', 'BLUE'], dtype='<U10')

In [4]:
#b. Use a numpy function to count the number of times the letter “a” appears in each element of your array.
np.char.count(four_strings,'a')

array([0, 0, 1, 0])

In [5]:
#c. Optional: Use a numpy function to find the length of each element in the array. You may need to Google this.
mylen = np.vectorize(len)
print (mylen(four_strings))

[ 6  7 10  4]


In [6]:
#2) Create an array containing EVERY OTHER odd number starting with 1 and ending with (and including) 45.
everyother_odd_number=np.arange(1,47,4)
everyother_odd_number


array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

In [7]:
# a. Use numpy to find the sum and the product of the elements of this array.
np.sum(everyother_odd_number)

276

In [8]:
np.prod(everyother_odd_number)

616159193

In [9]:
#b. Use numpy to take the natural log of each element.
np.log(everyother_odd_number)

array([0.        , 1.60943791, 2.19722458, 2.56494936, 2.83321334,
       3.04452244, 3.21887582, 3.36729583, 3.49650756, 3.61091791,
       3.71357207, 3.80666249])

In [10]:
#c. Optional: The numpy function np.diff finds the difference between adjacent elements of an array. 
#Find the SUM of adjacent elements of this array.

numb1=np.delete(everyother_odd_number,0)
numb1

array([ 5,  9, 13, 17, 21, 25, 29, 33, 37, 41, 45])

In [11]:
numb2=np.delete(everyother_odd_number,11)
numb2

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37, 41])

In [12]:
numb1+numb2

array([ 6, 14, 22, 30, 38, 46, 54, 62, 70, 78, 86])